// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: helloworld/v1/todo.proto

package v1

import (
	validate "github.com/envoyproxy/protoc-gen-validate/validate"
	annotations "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Symbols defined in public import of google/api/annotations.proto.

var E_Http = annotations.E_Http

// Symbols defined in public import of validate/validate.proto.

type KnownRegex = validate.KnownRegex

const KnownRegex_UNKNOWN = validate.KnownRegex_UNKNOWN
const KnownRegex_HTTP_HEADER_NAME = validate.KnownRegex_HTTP_HEADER_NAME
const KnownRegex_HTTP_HEADER_VALUE = validate.KnownRegex_HTTP_HEADER_VALUE

var KnownRegex_name = validate.KnownRegex_name
var KnownRegex_value = validate.KnownRegex_value

type FieldRules = validate.FieldRules
type FieldRules_Float = validate.FieldRules_Float
type FieldRules_Double = validate.FieldRules_Double
type FieldRules_Int32 = validate.FieldRules_Int32
type FieldRules_Int64 = validate.FieldRules_Int64
type FieldRules_Uint32 = validate.FieldRules_Uint32
type FieldRules_Uint64 = validate.FieldRules_Uint64
type FieldRules_Sint32 = validate.FieldRules_Sint32
type FieldRules_Sint64 = validate.FieldRules_Sint64
type FieldRules_Fixed32 = validate.FieldRules_Fixed32
type FieldRules_Fixed64 = validate.FieldRules_Fixed64
type FieldRules_Sfixed32 = validate.FieldRules_Sfixed32
type FieldRules_Sfixed64 = validate.FieldRules_Sfixed64
type FieldRules_Bool = validate.FieldRules_Bool
type FieldRules_String_ = validate.FieldRules_String_
type FieldRules_Bytes = validate.FieldRules_Bytes
type FieldRules_Enum = validate.FieldRules_Enum
type FieldRules_Repeated = validate.FieldRules_Repeated
type FieldRules_Map = validate.FieldRules_Map
type FieldRules_Any = validate.FieldRules_Any
type FieldRules_Duration = validate.FieldRules_Duration
type FieldRules_Timestamp = validate.FieldRules_Timestamp
type FloatRules = validate.FloatRules
type DoubleRules = validate.DoubleRules
type Int32Rules = validate.Int32Rules
type Int64Rules = validate.Int64Rules
type UInt32Rules = validate.UInt32Rules
type UInt64Rules = validate.UInt64Rules
type SInt32Rules = validate.SInt32Rules
type SInt64Rules = validate.SInt64Rules
type Fixed32Rules = validate.Fixed32Rules
type Fixed64Rules = validate.Fixed64Rules
type SFixed32Rules = validate.SFixed32Rules
type SFixed64Rules = validate.SFixed64Rules
type BoolRules = validate.BoolRules
type StringRules = validate.StringRules

const Default_StringRules_Strict = validate.Default_StringRules_Strict

type StringRules_Email = validate.StringRules_Email
type StringRules_Hostname = validate.StringRules_Hostname
type StringRules_Ip = validate.StringRules_Ip
type StringRules_Ipv4 = validate.StringRules_Ipv4
type StringRules_Ipv6 = validate.StringRules_Ipv6
type StringRules_Uri = validate.StringRules_Uri
type StringRules_UriRef = validate.StringRules_UriRef
type StringRules_Address = validate.StringRules_Address
type StringRules_Uuid = validate.StringRules_Uuid
type StringRules_WellKnownRegex = validate.StringRules_WellKnownRegex
type BytesRules = validate.BytesRules
type BytesRules_Ip = validate.BytesRules_Ip
type BytesRules_Ipv4 = validate.BytesRules_Ipv4
type BytesRules_Ipv6 = validate.BytesRules_Ipv6
type EnumRules = validate.EnumRules
type MessageRules = validate.MessageRules
type RepeatedRules = validate.RepeatedRules
type MapRules = validate.MapRules
type AnyRules = validate.AnyRules
type DurationRules = validate.DurationRules
type TimestampRules = validate.TimestampRules

var E_Disabled = validate.E_Disabled
var E_Ignored = validate.E_Ignored
var E_Required = validate.E_Required
var E_Rules = validate.E_Rules

// Todo priority
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_LOW         Priority = 1
	Priority_PRIORITY_MEDIUM      Priority = 2
	Priority_PRIORITY_HIGH        Priority = 3
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_MEDIUM",
		3: "PRIORITY_HIGH",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         1,
		"PRIORITY_MEDIUM":      2,
		"PRIORITY_HIGH":        3,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_helloworld_v1_todo_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_helloworld_v1_todo_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_helloworld_v1_todo_proto_rawDescGZIP(), []int{0}
}

// Todo status
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_PENDING     Status = 1
	Status_STATUS_COMPLETED   Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_PENDING",
		2: "STATUS_COMPLETED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_PENDING":     1,
		"STATUS_COMPLETED":   2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_helloworld_v1_todo_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_helloworld_v1_todo_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_helloworld_v1_todo_proto_rawDescGZIP(), []int{1}
}

// Todo message
type Todo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Priority      Priority               `protobuf:"varint,4,opt,name=priority,proto3,enum=helloworld.v1.Priority" json:"priority,omitempty"`
	Status        Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=helloworld.v1.Status" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todo) Reset() {
	*x = Todo{}
	mi := &file_helloworld_v1_todo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_todo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_todo_proto_rawDescGZIP(), []int{0}
}

func (x *Todo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Todo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Todo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Todo) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *Todo) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Todo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Todo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Create todo request
type CreateTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Priority      Priority               `protobuf:"varint,3,opt,name=priority,proto3,enum=helloworld.v1.Priority" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoRequest) Reset() {
	*x = CreateTodoRequest{}
	mi := &file_helloworld_v1_todo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoRequest) ProtoMessage() {}

func (x *CreateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_todo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoRequest.ProtoReflect.Descriptor instead.
func (*CreateTodoRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_todo_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTodoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTodoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTodoRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

// Get todo request
type GetTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodoRequest) Reset() {
	*x = GetTodoRequest{}
	mi := &file_helloworld_v1_todo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoRequest) ProtoMessage() {}

func (x *GetTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_todo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoRequest.ProtoReflect.Descriptor instead.
func (*GetTodoRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_todo_proto_rawDescGZIP(), []int{2}
}

func (x *GetTodoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Update todo request
type UpdateTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Priority      Priority               `protobuf:"varint,4,opt,name=priority,proto3,enum=helloworld.v1.Priority" json:"priority,omitempty"`
	Status        Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=helloworld.v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTodoRequest) Reset() {
	*x = UpdateTodoRequest{}
	mi := &file_helloworld_v1_todo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoRequest) ProtoMessage() {}

func (x *UpdateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_todo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoRequest.ProtoReflect.Descriptor instead.
func (*UpdateTodoRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_todo_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTodoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTodoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateTodoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTodoRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *UpdateTodoRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

// Delete todo request
type DeleteTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTodoRequest) Reset() {
	*x = DeleteTodoRequest{}
	mi := &file_helloworld_v1_todo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoRequest) ProtoMessage() {}

func (x *DeleteTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_todo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoRequest.ProtoReflect.Descriptor instead.
func (*DeleteTodoRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_todo_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTodoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// List todos request
type ListTodosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Priority      Priority               `protobuf:"varint,3,opt,name=priority,proto3,enum=helloworld.v1.Priority" json:"priority,omitempty"`
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=helloworld.v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodosRequest) Reset() {
	*x = ListTodosRequest{}
	mi := &file_helloworld_v1_todo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosRequest) ProtoMessage() {}

func (x *ListTodosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_todo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodosRequest.ProtoReflect.Descriptor instead.
func (*ListTodosRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_todo_proto_rawDescGZIP(), []int{5}
}

func (x *ListTodosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTodosRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTodosRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *ListTodosRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

// List todos response
type ListTodosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todos         []*Todo                `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodosResponse) Reset() {
	*x = ListTodosResponse{}
	mi := &file_helloworld_v1_todo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosResponse) ProtoMessage() {}

func (x *ListTodosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_todo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodosResponse.ProtoReflect.Descriptor instead.
func (*ListTodosResponse) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_todo_proto_rawDescGZIP(), []int{6}
}

func (x *ListTodosResponse) GetTodos() []*Todo {
	if x != nil {
		return x.Todos
	}
	return nil
}

func (x *ListTodosResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTodosResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTodosResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_helloworld_v1_todo_proto protoreflect.FileDescriptor

const file_helloworld_v1_todo_proto_rawDesc = "" +
	"\n" +
	"\x18helloworld/v1/todo.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17validate/validate.proto\"\xf0\x01\n" +
	"\x04Todo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x123\n" +
	"\bpriority\x18\x04 \x01(\x0e2\x17.helloworld.v1.PriorityR\bpriority\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.helloworld.v1.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"\x89\x01\n" +
	"\x11CreateTodoRequest\x12\x1d\n" +
	"\x05title\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x123\n" +
	"\bpriority\x18\x03 \x01(\x0e2\x17.helloworld.v1.PriorityR\bpriority\")\n" +
	"\x0eGetTodoRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\"\xc8\x01\n" +
	"\x11UpdateTodoRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x123\n" +
	"\bpriority\x18\x04 \x01(\x0e2\x17.helloworld.v1.PriorityR\bpriority\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.helloworld.v1.StatusR\x06status\",\n" +
	"\x11DeleteTodoRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\"\xbb\x01\n" +
	"\x10ListTodosRequest\x12\x1b\n" +
	"\x04page\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02(\x01R\x04page\x12&\n" +
	"\tpage_size\x18\x02 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x01R\bpageSize\x123\n" +
	"\bpriority\x18\x03 \x01(\x0e2\x17.helloworld.v1.PriorityR\bpriority\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.helloworld.v1.StatusR\x06status\"\x85\x01\n" +
	"\x11ListTodosResponse\x12)\n" +
	"\x05todos\x18\x01 \x03(\v2\x13.helloworld.v1.TodoR\x05todos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize*^\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_MEDIUM\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x03*J\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x01\x12\x14\n" +
	"\x10STATUS_COMPLETED\x10\x022\xe3\x03\n" +
	"\vTodoService\x12Y\n" +
	"\n" +
	"CreateTodo\x12 .helloworld.v1.CreateTodoRequest\x1a\x13.helloworld.v1.Todo\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/api/todo\x12U\n" +
	"\aGetTodo\x12\x1d.helloworld.v1.GetTodoRequest\x1a\x13.helloworld.v1.Todo\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/todo/{id}\x12^\n" +
	"\n" +
	"UpdateTodo\x12 .helloworld.v1.UpdateTodoRequest\x1a\x13.helloworld.v1.Todo\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/api/todo/{id}\x12^\n" +
	"\n" +
	"DeleteTodo\x12 .helloworld.v1.DeleteTodoRequest\x1a\x16.google.protobuf.Empty\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/api/todo/{id}\x12b\n" +
	"\tListTodos\x12\x1f.helloworld.v1.ListTodosRequest\x1a .helloworld.v1.ListTodosResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/api/todosBP\n" +
	"\x1cdev.kratos.api.helloworld.v1B\vTodoProtoV1P\x01Z!todo-service/api/helloworld/v1;v1P\x00P\x02b\x06proto3"

var (
	file_helloworld_v1_todo_proto_rawDescOnce sync.Once
	file_helloworld_v1_todo_proto_rawDescData []byte
)

func file_helloworld_v1_todo_proto_rawDescGZIP() []byte {
	file_helloworld_v1_todo_proto_rawDescOnce.Do(func() {
		file_helloworld_v1_todo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_v1_todo_proto_rawDesc), len(file_helloworld_v1_todo_proto_rawDesc)))
	})
	return file_helloworld_v1_todo_proto_rawDescData
}

var file_helloworld_v1_todo_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_helloworld_v1_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_helloworld_v1_todo_proto_goTypes = []any{
	(Priority)(0),             // 0: helloworld.v1.Priority
	(Status)(0),               // 1: helloworld.v1.Status
	(*Todo)(nil),              // 2: helloworld.v1.Todo
	(*CreateTodoRequest)(nil), // 3: helloworld.v1.CreateTodoRequest
	(*GetTodoRequest)(nil),    // 4: helloworld.v1.GetTodoRequest
	(*UpdateTodoRequest)(nil), // 5: helloworld.v1.UpdateTodoRequest
	(*DeleteTodoRequest)(nil), // 6: helloworld.v1.DeleteTodoRequest
	(*ListTodosRequest)(nil),  // 7: helloworld.v1.ListTodosRequest
	(*ListTodosResponse)(nil), // 8: helloworld.v1.ListTodosResponse
	(*emptypb.Empty)(nil),     // 9: google.protobuf.Empty
}
var file_helloworld_v1_todo_proto_depIdxs = []int32{
	0,  // 0: helloworld.v1.Todo.priority:type_name -> helloworld.v1.Priority
	1,  // 1: helloworld.v1.Todo.status:type_name -> helloworld.v1.Status
	0,  // 2: helloworld.v1.CreateTodoRequest.priority:type_name -> helloworld.v1.Priority
	0,  // 3: helloworld.v1.UpdateTodoRequest.priority:type_name -> helloworld.v1.Priority
	1,  // 4: helloworld.v1.UpdateTodoRequest.status:type_name -> helloworld.v1.Status
	0,  // 5: helloworld.v1.ListTodosRequest.priority:type_name -> helloworld.v1.Priority
	1,  // 6: helloworld.v1.ListTodosRequest.status:type_name -> helloworld.v1.Status
	2,  // 7: helloworld.v1.ListTodosResponse.todos:type_name -> helloworld.v1.Todo
	3,  // 8: helloworld.v1.TodoService.CreateTodo:input_type -> helloworld.v1.CreateTodoRequest
	4,  // 9: helloworld.v1.TodoService.GetTodo:input_type -> helloworld.v1.GetTodoRequest
	5,  // 10: helloworld.v1.TodoService.UpdateTodo:input_type -> helloworld.v1.UpdateTodoRequest
	6,  // 11: helloworld.v1.TodoService.DeleteTodo:input_type -> helloworld.v1.DeleteTodoRequest
	7,  // 12: helloworld.v1.TodoService.ListTodos:input_type -> helloworld.v1.ListTodosRequest
	2,  // 13: helloworld.v1.TodoService.CreateTodo:output_type -> helloworld.v1.Todo
	2,  // 14: helloworld.v1.TodoService.GetTodo:output_type -> helloworld.v1.Todo
	2,  // 15: helloworld.v1.TodoService.UpdateTodo:output_type -> helloworld.v1.Todo
	9,  // 16: helloworld.v1.TodoService.DeleteTodo:output_type -> google.protobuf.Empty
	8,  // 17: helloworld.v1.TodoService.ListTodos:output_type -> helloworld.v1.ListTodosResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_helloworld_v1_todo_proto_init() }
func file_helloworld_v1_todo_proto_init() {
	if File_helloworld_v1_todo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_v1_todo_proto_rawDesc), len(file_helloworld_v1_todo_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_v1_todo_proto_goTypes,
		DependencyIndexes: file_helloworld_v1_todo_proto_depIdxs,
		EnumInfos:         file_helloworld_v1_todo_proto_enumTypes,
		MessageInfos:      file_helloworld_v1_todo_proto_msgTypes,
	}.Build()
	File_helloworld_v1_todo_proto = out.File
	file_helloworld_v1_todo_proto_goTypes = nil
	file_helloworld_v1_todo_proto_depIdxs = nil
}
